from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import InMemorySaver
from langchain_core.messages import AnyMessage, SystemMessage, AIMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

from dotenv import load_dotenv
import os
import uuid
import operator
from typing_extensions import TypedDict, Annotated

from langchain_groq import ChatGroq

load_dotenv()

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

# --- Prompt & chain defined once at module level (not rebuilt per call) ---
prompt = ChatPromptTemplate.from_messages([
    ("system", """You are Jarvis, a helpful AI assistant. Use conversation memory properly 
                  and answer based on the previous messages."""),
    MessagesPlaceholder(variable_name="messages")
])

chain = prompt | llm

# Shared memory state
class MessageState(TypedDict):
    messages: Annotated[list[AnyMessage], operator.add]
    llm_calls: int

def chatbot_node(state: MessageState):
    try:
        response = chain.invoke({"messages": state["messages"]})
    except Exception as e:
        response = AIMessage(content=f"Sorry, I encountered an error: {e}")

    return {
        "messages": [response],
        "llm_calls": state["llm_calls"] + 1
    }

builder = StateGraph(MessageState)
builder.add_node("chatbot", chatbot_node)
builder.add_edge(START, "chatbot")
builder.add_edge("chatbot", END)

# Add short term memory checkpointing
memory = InMemorySaver()
app = builder.compile(checkpointer=memory)

# Dynamic thread_id so each run starts a fresh isolated session
config = {"configurable": {"thread_id": str(uuid.uuid4())}}

print("Memory system initialized, type exit or quit to close...")
print("-" * 50)

total_llm_calls = 0

while True:
    user_input = input("\nYou: ")
    if user_input.lower() in ['quit', 'exit']:
        print(f"\nJarvis: Goodbye! 👋  (Session used {total_llm_calls} LLM call(s))")
        break

    inputs = {"messages": [HumanMessage(content=user_input)], "llm_calls": total_llm_calls}

    for event in app.stream(inputs, config=config):
        for node_name, node_state in event.items():
            if node_name == "chatbot":
                total_llm_calls = node_state["llm_calls"]
                # Print the content of the very last message generated by the LLM
                print(f"Jarvis: {node_state['messages'][-1].content}")